### ISSUE TITLE
KMS Support

### ISSUE THREAD

**Issue by mikegrima** [Netflix-Skunkworks/raven-python-lambda#1]
Support KMS for Sentry DSN

Add an env var for this.

**Comment by kevgliss** [comment]
I'm not sure we want to solve this directly in the plugin itself. I assume that users would want a more comprehensive way of encrypting/decrypting sensitive variables. 

There seem to be quite a few community plugins that support this:
https://github.com/SC5/serverless-kms-secrets

We should probably pick one to recommend or simply point out the fact you might want to encrypt your DSN.
