### ISSUE TITLE
Sentry is not disabled in local environment

### ISSUE THREAD

**Issue by Tethik** [Netflix-Skunkworks/raven-python-lambda#23]
![2018-01-05-161812_594x161_scrot](https://user-images.githubusercontent.com/298627/34615192-4c7883fc-f234-11e7-9050-93f2e839ef3a.png)

Well this is awkward :laughing: 

It seems like all it does when local is display a warning. Would also be good to include that a local environment is detected by IS_OFFLINE or IS_LOCAL.

**Comment by kevgliss** [comment]
FYI, 0.1.5 has been released. Sorry for the delay.
