### ISSUE TITLE
Could you release the new version?

### ISSUE THREAD

**Issue by ghost** [Netflix-Skunkworks/raven-python-lambda#29]
I'm facing an error when invoking lambda function locally and it's fixed by [this commit](https://github.com/Netflix-Skunkworks/raven-python-lambda/commit/afe25c9a1e5e24f261e869d09a146e1d3936f6a5)

Could you bump the version to 0.1.6? so that we can all get the fix from `pip install raven-python-lambda`?

Thanks

**Comment by mikegrima** [comment]
I'll get this done tomorrow morning.

**Comment by mikegrima** [comment]
Version 0.1.6 addressed in #30

**Comment by mikegrima** [comment]
0.1.6 pushed to PyPI.
